server:
  port: 8080
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      username: chris
      password: chris
      database: chat-historial
      port: 27017
