services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chris
      MONGO_INITDB_ROOT_PASSWORD: chris

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chris
      ME_CONFIG_MONGODB_ADMINPASSWORD: chris
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  default:
    name: mongodb_network